import { Hospital } from "./hospital"

export const HOSPITALS:Hospital[] = [
    {
      index:1,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:2,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:3,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:4,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:5,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:6,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:7,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:8,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:9,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:10,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:11,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:12,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:13,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:14,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:15,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:16,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:17,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:18,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:19,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:20,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:21,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:22,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:23,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: false
    },
    {
      index:24,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:25,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:26,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
  ]