import { Hospital } from "./hospital"

export const HOSPITALS:Hospital[] = [
    {
      index:1,
      hospitalName: "TEST1",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:2,
      hospitalName: "TEST2",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:3,
      hospitalName: "TEST3",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:4,
      hospitalName: "TEST4",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:5,
      hospitalName: "TEST5",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:6,
      hospitalName: "TEST6",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:7,
      hospitalName: "TEST7",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:8,
      hospitalName: "TEST8",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:9,
      hospitalName: "TEST9",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:10,
      hospitalName: "TEST10",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:11,
      hospitalName: "TEST11",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:12,
      hospitalName: "TEST12",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:13,
      hospitalName: "TEST13",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:14,
      hospitalName: "TEST14",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:15,
      hospitalName: "TEST15",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:16,
      hospitalName: "TEST16",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:17,
      hospitalName: "TEST17",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:18,
      hospitalName: "TEST18",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:19,
      hospitalName: "TEST19",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:20,
      hospitalName: "TEST20",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:21,
      hospitalName: "TEST21",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:22,
      hospitalName: "TEST22",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:23,
      hospitalName: "TEST23",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: false
    },
    {
      index:24,
      hospitalName: "TEST24",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:25,
      hospitalName: "TEST25",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
    {
      index:26,
      hospitalName: "TEST26",
      registrationDate: "Jul 8, 2022, 12:01:52 PM",
      numberOfBeds:256,
      numberOfDevice:253,
      numberOfAllocatedDevice:248,
      roomName:"TShospital1",
      status: "Activated",
      delete: true,
      self: true
    },
  ]